SELECT
    COLUMN_NAME,
    COLUMN_DEFAULT,
    IS_NULLABLE,
    DATA_TABLE,
    CHARACTER_MAXIMUM_LENGHT,
    NUMERIC_TYPE,
    NUMERIC_SCALE,
    COLUMN_TYPE,
    COLUMN_KEY,
    EXTRA,
    PRIVILEGES,
    COLUMN_COMMENT
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE        
    TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'books';